numero = input('Digite um número: ')
#numero = numero.split()
numero = numero.zfill(4)
print(f'Unidade: {numero[3]}')
print(f'Dezena: {numero[2]}')
print(f'Centena: {numero[1]}')
print(f'Milhar: {numero[0]}')